# Generated by Django 3.2.12 on 2022-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Reading', models.CharField(default=None, max_length=100)),
                ('D_Spelling', models.CharField(default=None, max_length=100)),
                ('D_Handwriting', models.CharField(default=None, max_length=100)),
                ('D_Maths', models.CharField(default=None, max_length=100)),
                ('D_Attention', models.CharField(default=None, max_length=100)),
                ('D_Memory', models.CharField(default=None, max_length=100)),
                ('D_Language', models.CharField(default=None, max_length=100)),
                ('D_Subject', models.CharField(default=None, max_length=100)),
                ('D_Concentration', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'DisabilityTest',
            },
        ),
    ]
