# Generated by Django 3.2.12 on 2022-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0002_disabilitytest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disabilitytest',
            old_name='D_Concentration',
            new_name='D_BasicArithmetic',
        ),
        migrations.RenameField(
            model_name='disabilitytest',
            old_name='D_Language',
            new_name='D_HigherArithmetic',
        ),
        migrations.RenameField(
            model_name='disabilitytest',
            old_name='D_Maths',
            new_name='D_LearningLanguage',
        ),
        migrations.RenameField(
            model_name='disabilitytest',
            old_name='D_Subject',
            new_name='D_LearningSubject',
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='D_StudySkills',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='D_WrittenExpression',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='Does_Not_like_School',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='Easily_Distracted',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='Lack_Motivation',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='Repeated_a_Grade',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='disabilitytest',
            name='Slow_To_Learn',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
