# Generated by Django 3.2.12 on 2022-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0004_disabilitytest_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'admindata',
            },
        ),
    ]
