# Generated by Django 3.1.3 on 2022-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0005_admindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Learning_Disability', models.CharField(default=None, max_length=100, null=True)),
                ('Maths_Test', models.CharField(default=None, max_length=100, null=True)),
                ('Grammar_Test', models.CharField(default=None, max_length=100, null=True)),
                ('Reading_Test', models.CharField(default=None, max_length=100, null=True)),
                ('Memory_images', models.CharField(default=None, max_length=100, null=True)),
                ('Memory_audio', models.CharField(default=None, max_length=100, null=True)),
                ('Scenario_Test', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TestResult',
            },
        ),
        migrations.AlterField(
            model_name='admindata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='disabilitytest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
