# Generated by Django 3.1.3 on 2022-05-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0006_auto_20220515_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Date',
            field=models.DateField(default=None, max_length=100, null=True),
        ),
    ]
