# Generated by Django 3.1.3 on 2022-06-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0007_testresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Users_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
