# Generated by Django 3.1.3 on 2022-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0008_testresult_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Video_test1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='Video_test2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='Video_test3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
