# Generated by Django 3.1.3 on 2022-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClassificationOfLD', '0009_auto_20220602_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='Dyscalculia',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='Dysgraphia',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='Dyslexia',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
